#!/bin/bash

# Declare branch(s) to protect
declare -a protected_branch=('master' '3.0')

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
for branch in "${protected_branch[@]}"
do
    if [ $branch = $current_branch ]; then
        read -p "You're about to push $branch, are you sure? [y/n] " -n 1 -r < /dev/tty
        echo
        if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
            exit 0
        fi
        exit 1
    fi
done
